### ISSUE TITLE
node sass error

### ISSUE THREAD

**Issue by tygas** [gokercebeci/loopback-react#2]
After fresh instalation

`./src/styles/App.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/styles/App.scss)
Module not found: Can't resolve '../components/Welcome/img/intro-header-bg.jpg' in '/Users/tygas/WebstormProjects/developer-dashboard/loopback-react/client/src/styles'
`

**Comment by gokerDEV** [comment]
It fixed on commit dd91ed094e6659f00eafbf221cd23d26a278b7c8
